### ISSUE TITLE
Make a Gregtech Community Edition Version

### ISSUE THREAD

**Issue by Blocky106** [NotMyWing/NAE2#17]
make a ce version
please

**Comment by NotMyWing** [comment]
I'm not entirely sure what this issue is about. If you're referencing https://github.com/NotMyWing/NAE2/issues/13, then I already stated that it's implemented in GTCEu itself. That being said, there's no logic in this mod that's specific to GregTech at all.

GTCE has reached the end of its life, with GTCEu picking up from where it stopped getting any updates, so you should be using it instead.

**Comment by NotMyWing** [comment]
Closing since it's been a week without a follow-up.
