### ISSUE TITLE
Is the Beam Former beam performance heavy?

### ISSUE THREAD

**Issue by ChromaPIE** [NotMyWing/NAE2#22]
It's such a handy tool especially when you got a huge base and you have to wander around wrenching stuff but dont want cables to slow you down.

And thats where the problem is. ppl can easily overuse it, and i believe it was designed to make ppl overuse it (i dont mean using it for a 1 block gap tho), so i wonder if it can actually impact the performance, especially for rendering. If it is, will there be a clientside config option to enable a faster kind of beam?

I dont actually know how to test it by myself. My current base in E2E-E is already laggy asf

**Comment by NotMyWing** [comment]
Backend-wise, ME Beam Formers operate only on block and network events, so they don't spontaneously check the LOS when idling. Otherwise, they sleep and don't do anything at all.

When alerted, the only thing they do is going through the 32 blocks directly in front to determine if a connection can be made/kept. The connection is the same kind as the ones native AE2 cables create, so it's all just basic AE2 stuff.

On the client, the only taxing thing is the beam itself, which can be turned off at will with any wrench if desired. Beam Formers also create light, which is hardly a problem if you have Phosphorus installed.

**Comment by ChromaPIE** [comment]
thats awesome. didnt know the beam is toggleable. thanks for the reply!

**Comment by ChromaPIE** [comment]
I tried wrenching the former to turn the beam off, i might be doing it wrong but it's not actually working for me, every second right clicking on it shows _Showing beam._ in the chat, and that's all that happened.

**Comment by NotMyWing** [comment]
That's concerning, it worked just fine for me all the time. What wrench? Server or single?

**Comment by NotMyWing** [comment]
Looking into it.
